# project:
log_dir: './logs'
project: "lsun_church"
exp: "test"
log: ["schedule_sampler"]

# data:
data_dir: "./data/lsun_church"
image_size: 256

# model:
num_channels: 256
num_res_blocks: 2
num_heads: 1
num_heads_upsample: -1
num_head_channels: 64
attention_resolutions: "32,16,8"
channel_mult: ""
dropout: 0.1
class_cond: False
use_scale_shift_norm: True
resblock_updown: True
use_fp16: True
use_new_attention_order: False

# discriminator:
use_discriminator: False
t_dim: 2

# diffusion:
learn_sigma: False
diffusion_steps: 1000
noise_schedule: "linear"
timestep_respacing: ""
use_kl: False
predict_xstart: False
rescale_timesteps: False
rescale_learned_sigmas: False
schedule_sampler: "uniform" # "pair, uniform"

# training:
# resume
use_checkpoint: False
resume_checkpoint: ""
# batch
batch_size: 16
microbatch: -1  # -1 disables microbatches
# about losses
lr_model: 1e-4
lr_disc: 1e-4
lossD_type: "hinge"
lossG_weight: 0.0
grad_weight: 0.5
# saving
ema_rate: '0.9999'
log_interval: 5000
save_interval: 30000
sample_num: 64
sample_type: ["ddim20", "ddim10"]
# etc
fp16_scale_growth: 0.001
weight_decay: 0.0
lr_anneal_steps: 200000